steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/meme-maker:$TAG_NAME', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', 'gcr.io/$PROJECT_ID/meme-maker:$TAG_NAME','--entrypoint="python', 'test-makememe.py']
images: ['gcr.io/$PROJECT_ID/meme-maker:$TAG_NAME']
