steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/meme-maker:$TAG_NAME', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '--entrypoint=python','gcr.io/$PROJECT_ID/meme-maker:$TAG_NAME','test-makememe.py']
images: ['gcr.io/$PROJECT_ID/meme-maker:$TAG_NAME']
