apiVersion: v1
kind: Service
metadata:
  labels:
    app: mememaker
  name: mememaker 
spec:
  ports:
  - name: flask 
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    load-balancer-mememaker: "true"
  sessionAffinity: None
  type: NodePort
